version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment: # Variáveis de ambiente para configurar o PostgreSQL
      POSTGRES_USER: darlan
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes: # Volume para persistir os dados do banco
      - postgres-data:/var/lib/postgresql/data
    networks:
      - desafio

  api:
    container_name: api-darlan
    build: ./backend
    ports:
      - "3000:3000"
    env_file: # Arquivo de variáveis de ambiente para configurar o backend
      - ./backend/.env
    depends_on: # a api depende do postgres para funcionar
      - postgres
    networks:
      - desafio

  app:
    container_name: app-darlan
    build: ./frontend
    ports:
      - "3007:3007"
    depends_on: # o app depende da api para funcionar
      - api
    networks:
      - desafio

networks:
  desafio:

volumes:
  postgres-data:
