version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: darlan
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    container_name: api-darlan
    build: ./backend
    ports:
      - "5002:5002"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres

volumes:
  postgres-data:
